site_name: TTK Online Example Database

#theme:
    #name: material
    #palette:
      #primary: indigo
      #scheme: default

theme:
  name: material
  features:
    - content.code.copy
  palette: #
    - scheme: slate #
      primary: teal
      accent: teal
      display.background_color: grey
      background-color: grey


markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.arithmatex
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink
    - admonition
    - codehilite:
        guess_lang: false
        use_pygments: true
    - footnotes
    - toc:
        permalink: true
